[project]
authors = ["neverorfrog <97flavio.maiorana@gmail.com>"]
channels = ["robostack-staging", "conda-forge"]
description = "Add a short description here"
name = "crazy-neural-mpc"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

# Build Commands
build-acados = "cd external/acados && mkdir -p build && cd build && cmake -DACADOS_WITH_QPOASES=ON -DACADOS_WITH_OSQP=ON .. && make -j8"
build-firmware = "cd external/crazyflie-firmware && mkdir -p sitl_make/build && cd $_ && cmake .. && make all"
build = "colcon build --symlink-install --base-paths src"
clean = "rm -rf install log build"

# Nodes
flocking = "ros2 launch crazyflie_flocking_pkg flocking.launch.py"
sim-multi = "cd external/crazyflie-firmware && bash tools/crazyflie-simulation/simulator_files/gazebo/launch/sitl_multiagent_square.sh -n 4 -m crazyflie"
sim = "cd external/crazyflie-firmware && bash tools/crazyflie-simulation/simulator_files/gazebo/launch/sitl_singleagent.sh -m crazyflie -x 0 -y 0"
swarm = "ros2 launch crazyflie_swarm_pkg swarm.launch.py"
teleop = 'ros2 launch crazyflie_swarm_pkg teleop.launch.py'
mpc = "ros2 launch crazyflie_mpc_pkg mpc.launch.py"
crazyswarm = "ros2 launch crazyflie launch.py backend:=cflib"
record = "cd crazy_bag && ros2 bag record --all"

# Services
takeoff = 'ros2 service call /take_off crazyflie_swarm_interfaces/srv/TakeOff "{height: 0.35, duration: 5}"'
land = 'ros2 service call /land crazyflie_swarm_interfaces/srv/Land "{duration: 3}"'
mpc-takeoff = 'ros2 service call /mpc_takeoff crazyflie_swarm_interfaces/srv/TakeOff "{height: 0.35, duration: 2}"'
mpc-land = 'ros2 service call /mpc_land crazyflie_swarm_interfaces/srv/Land "{duration: 3}"'
mpc-hover = 'ros2 service call /mpc_hover std_srvs/Empty "{}"'
mpc-traj = 'ros2 service call /mpc_traj std_srvs/Empty "{}"'

[pypi-dependencies]
cflib = {path = "external/crazyflie-lib-python", editable = true}
acados_template = {path = "external/acados/interfaces/acados_template", editable = true}
rowan = ">=1.3.2, <2"
transforms3d = ">=0.4.2, <0.5"
omegaconf = ">=2.3.0, <3"
jinja2 = ">=3.1.4, <4"
casadi = "==3.6.4"
torch = "*"
pyyaml = ">=6.0.2,<7"

[dependencies]
python = "3.11.*"
numpy = "==1.24"
colcon-common-extensions = ">=0.3.0,<0.4"
setuptools = ">=75.6.0,<76"
ros-humble-desktop = "==0.10.0"
ros-humble-tf2 = ">=0.25.5,<0.26"
ros-humble-ros-gz-bridge = ">=0.244.9"
ros-humble-tf-transformations = ">=1.0.1,<2"

[activation]
scripts = ["install/setup.sh"]